version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - TZ=Asia/Tokyo
    networks:
      - app_network
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: yarn dev
    volumes:
      - ./frontend:/app
    environment:
      - TZ=Asia/Tokyo
    networks:
      - app_network
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=172.0.0.1
    networks:
      - app_network
    depends_on:
      - frontend
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
